### ISSUE TITLE
Support for ol.interaction.ExtentOptions and extentchanged event

### ISSUE THREAD

**Issue by gkresic** [TDesjardins/gwt-ol#145]
[ol.interaction.Extent](https://github.com/TDesjardins/gwt-ol/blob/master/gwt-ol3-client/src/main/java/ol/interaction/Extent.java) is missing constructor that would allow for customization.

There are no events for reacting when extent is changed on map, too.

If no one is working on this, I can provide a patch.

**Comment by TDesjardins** [comment]
Yes, you are right. Patches are welcome!
