### ISSUE TITLE
Support for polygon repeating patterns

### ISSUE THREAD

**Issue by csozoli** [TDesjardins/gwt-ol#147]
I am trying to convert a gwt openlayers 2 project to OL3+ and use this wrapper for this.
I am at the stage of replacing the old SLD-based styling by OL3+ conform styles.
There is however one thing I cannot do: drawing a repeated pattern over a polygon for rendering.
Based on the official OL example (https://openlayers.org/en/latest/examples/canvas-gradient-pattern.html) it should be possible to set a "colorlike" (e.g. CanvasPattern created dynamically) as fill color, but the wrapper currently accepts Color only and colorlike is not known across the gwt universe...
Not sure how to solve this problem, if there is any working example (GWT, not pure js), it is also welcome as reply.... Thanks Zoli

**Comment by TDesjardins** [comment]
Hello @csozoli ,

yes this is missing. I will have a look at this soon.

**Comment by csozoli** [comment]
Thank you

**Comment by TDesjardins** [comment]
[This commit](https://github.com/TDesjardins/gwt-ol/commit/dabe3aa74d7945608d6a4a0f71a47c2179bc7454) brings canvas gradient and pattern support to color properties of Fill and Stroke. You should now be able to do the things from the OL example. I close this issue. Please reopen if you have any further issues with this solution. 

P.S. If you will have an working example it would be great to integrate it in the gwt-ol demo.

**Comment by csozoli** [comment]
Thanks, I will take a look. If I have any example I will let you know

**Comment by csozoli** [comment]
We have a maven based system, my colleague says it is not released.

**Comment by TDesjardins** [comment]
I suppose you are using the snapshot repo? Seems that the snapshot isn't landed. I will check this.

**Comment by TDesjardins** [comment]
@csozoli Your colleague is right. Now the latest snapshot is online and you should be able to use it.

**Comment by csozoli** [comment]
Thanks. I will soon get to trying out the new feature.

**Comment by csozoli** [comment]
Actually, I wanted to have CanvasPattern, not CanvasGradient. I will see how I can at least try what there already is but my final goal is to add a repeating pattern (like slash-like lines) to a polygon area

**Comment by csozoli** [comment]
I am struggling with using elemental2 types, is there any special reason to use these instead of the standard gwt classes (CanvasGradient and CanvasPattern)?
I admit I don't know elemental2, but so far I could set up the gradient in gwt world and also in elemental world, however elemental2 consists only of interfaces and I have no means to convert the results to the required parameter types.
My colleague is starting to cheat and uses jinterop based functions to create the pattern but imho it should be possible with the stock OL wrapper, too.
Could you pls take a look / enlighten me?

**Comment by csozoli** [comment]
So we temporarily defined an extension to the FillOptions with jinterop using the standard com.google.gwt.canvas.dom.client classes:

`import com.google.gwt.canvas.client.Canvas;`
`import com.google.gwt.canvas.dom.client.CanvasGradient;`
`import com.google.gwt.canvas.dom.client.CanvasPattern;`
`import com.google.gwt.canvas.dom.client.Context2d;`
`import com.google.gwt.canvas.dom.client.Context2d.Repetition;`

`@JsType(isNative = true, namespace = JsPackage.GLOBAL, name = "Object")`
 `private static class EnhancedFillOptions extends FillOptions {`
&nbsp; &nbsp; ` @JsProperty`
 &nbsp; &nbsp; ` public native void setColor(CanvasGradient gradient);`
 
&nbsp; &nbsp; ` @JsProperty`
&nbsp; &nbsp; ` public native void setColor(CanvasPattern pattern);`
`}`

Then we could set up a CanvasPattern:

`protected CanvasPattern createPattern(int size, String color) {`
&nbsp; &nbsp; `Canvas canvas = Canvas.createIfSupported();`
&nbsp; &nbsp; `if (canvas != null) {`
&nbsp; &nbsp; &nbsp; &nbsp; `canvas.setCoordinateSpaceHeight(size);`
&nbsp; &nbsp; &nbsp; &nbsp; `canvas.setCoordinateSpaceWidth(size);`
&nbsp; &nbsp; &nbsp; &nbsp; `Context2d context = canvas.getContext2d();`
&nbsp; &nbsp; &nbsp; &nbsp; `context.beginPath();`
&nbsp; &nbsp; &nbsp; &nbsp; `context.moveTo(size, 0);`
&nbsp; &nbsp; &nbsp; &nbsp; `context.lineTo(0, size);`
&nbsp; &nbsp; &nbsp; &nbsp; `context.setStrokeStyle(color);`
&nbsp; &nbsp; &nbsp; &nbsp; `context.stroke();`
&nbsp; &nbsp; &nbsp; &nbsp; `return context.createPattern(canvas.getCanvasElement(), Repetition.REPEAT);`
&nbsp; &nbsp; `}`
&nbsp; &nbsp; `return null;`
`}`


And then 

`EnhancedFillOptions fo = OLFactory.createOptions();`
`...`
`CanvasPattern pattern = createPattern(size, patternColor);`
`if (pattern != null) {`
&nbsp; &nbsp; `fo.setColor(pattern);`	
`}`

**Comment by TDesjardins** [comment]
@csozoli I created an example for canvas pattern and gradient styling:

https://tdesjardins.github.io/gwt-ol/#CanvasGradientExample

source code:

https://github.com/TDesjardins/gwt-ol/blob/master/gwt-ol3-demo/src/main/java/com/github/tdesjardins/ol3/demo/client/example/CanvasGradientExample.java

> I am struggling with using elemental2 types, is there any special reason to use these instead of the standard gwt classes (CanvasGradient and CanvasPattern)?

Yes, you should use elemental2 if you want to code future-proof. Elemental2 works with J2CL and will work with GWT 3.

**Comment by csozoli** [comment]
Hi,

Apart from `ol.has.Has` completely missing from the wrapper (maybe you have some experimental build....), I will try to add the example to my code and see how it works.
Thanks in any case.

**Comment by TDesjardins** [comment]
@csozoli 
> I need to mention that code like
`(CanvasRenderingContext2D) (Object) canvas.getContext("2d")`
can only be written if someone exactly knows how these casts will be executed in the final js....

Yes, this isn't ideal, but nearer to JS than the "old" GWT-stuff. You are free to use /write factory or utility classes which can do the stuff you often need.
