### ISSUE TITLE
Support for functions in ol.style.Style

### ISSUE THREAD

**Issue by JohanBoman** [TDesjardins/gwt-ol#166]
The geometry and renderer attributes in ol.style.Style can be functions, would it be possible to implement this in gwt-ol?
Could probably be implemented in a similar way as StyleFunction (https://github.com/TDesjardins/gwt-ol/issues/90).
Is this something the people involved could fix or do you need a patch, not sure though in what timeframe i could provide that.

**Comment by TDesjardins** [comment]
@JohanBoman Thanks for the issue. Both features can added to gwt-ol.

> Could probably be implemented in a similar way as StyleFunction (#90).

Right, this is the generic way if the function has one input and one output parameter. You could also provide a special interface for every type of function. This is then necessary if the function has more than one input param.
I created a [PR](https://github.com/TDesjardins/gwt-ol/pull/167) to add the geometry function to style.

> Is this something the people involved could fix or do you need a patch, not sure though in what timeframe i could provide that.

Both ways are possible and contributions are welcome.

**Comment by TDesjardins** [comment]
@JohanBoman Both functions are implemented and merged in the current master branch. Could you test these?

**Comment by JohanBoman** [comment]
Thanks for the very quick fix!
Still on holiday, will try to test this as soon as possible, but will probably be at least some week(s)

**Comment by TDesjardins** [comment]
@JohanBoman I will close this issue. Please reopen if it not works for you.

**Comment by JohanBoman** [comment]
sorry about not getting back here, im sorry to say that i have not tested this yet.
Will reopen if/when i eventually get back to this on my side.
thanks again for the quick action!
